// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// gwpcorRcpp
List gwpcorRcpp(NumericMatrix dMat, double bw, NumericMatrix x, String kernel, bool adaptive, int nn);
RcppExport SEXP _gwpcormapper_gwpcorRcpp(SEXP dMatSEXP, SEXP bwSEXP, SEXP xSEXP, SEXP kernelSEXP, SEXP adaptiveSEXP, SEXP nnSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type dMat(dMatSEXP);
    Rcpp::traits::input_parameter< double >::type bw(bwSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< String >::type kernel(kernelSEXP);
    Rcpp::traits::input_parameter< bool >::type adaptive(adaptiveSEXP);
    Rcpp::traits::input_parameter< int >::type nn(nnSEXP);
    rcpp_result_gen = Rcpp::wrap(gwpcorRcpp(dMat, bw, x, kernel, adaptive, nn));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_gwpcormapper_gwpcorRcpp", (DL_FUNC) &_gwpcormapper_gwpcorRcpp, 6},
    {NULL, NULL, 0}
};

RcppExport void R_init_gwpcormapper(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
