# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

gwpcorRcpp <- function(dMat, bw, x, kernel, adaptive, nn) {
    .Call(`_gwpcormapper_gwpcorRcpp`, dMat, bw, x, kernel, adaptive, nn)
}

